#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-audit #指定服务名
  #2.数据库连接池
  datasource:
    act:
      jdbc-url: ${IHRM_ACTIVITI_MYSQL_URL:jdbc:mysql://127.0.0.1:3306/act?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false}
      username: ${IHRM_ACTIVITI_MYSQL_USERNAME:${IHRM_MYSQL_USERNAME:root}}
      password: ${IHRM_ACTIVITI_MYSQL_PASSWORD:${IHRM_MYSQL_PASSWORD:}}
      driver-class-name: com.mysql.jdbc.Driver
    ihrm:
      jdbc-url: ${IHRM_MYSQL_URL:jdbc:mysql://127.0.0.1:3306/ihrm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false}
      username: ${IHRM_MYSQL_USERNAME:root}
      password: ${IHRM_MYSQL_PASSWORD:}
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: ${IHRM_REDIS_HOST:127.0.0.1}
    port: ${IHRM_REDIS_PORT:6379}
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  activiti:
    history-level: full
    db-history-used: true
    database-schema-update: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    preferIpAddress : true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#服务配置
server:
  port: 9007
hibernate:
  hbm2ddl:
    auto: none
  dialect: org.hibernate.dialect.MySQLDialect